package english.phrasesets;

/**
 * This phraseset class will be automatically populated with data from the 
 * phraseset project file.  Manual edits should only be outside of the tag 
 * areas or overridden methods. 
 * Class created on: 
 * Last generated by Orchestration Designer at: 2023-JUL-06  10:13:17 AM
 */
public class AllPhraseFiles extends com.avaya.sce.runtime.Phraseset { 

	//{{START:CLASS:FIELDS
	private static final com.avaya.sce.runtime.Phraseset.PhraseMap PHRASE_MAP;
	//}}END:CLASS:FIELDS

	/**
	 * Static initializer
	 */
	static {
		//{{START:PHRASESET:STATIC

		// Create the phrase map, then populate with phrases
		PHRASE_MAP = new com.avaya.sce.runtime.Phraseset.PhraseMap(26);
		com.avaya.sce.runtime.Phrase phrase;

		// phrase: Welcome_01
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "Welcome_01", "Welcome_01.wav", ""); 

		// phrase: CallCenterSpecialist
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "CallCenterSpecialist", "CallCenterSpecialist.wav", ""); 

		// phrase: CallMaybeRecorded
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "CallMaybeRecorded", "CallMaybeRecorded.wav", ""); 

		// phrase: BusyMessage
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "BusyMessage", "BusyMessage.wav", ""); 

		// phrase: ToGetCallBack
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "ToGetCallBack", "ToGetCallBack.wav", ""); 

		// phrase: CallYouDuringWH
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "CallYouDuringWH", "CallYouDuringWH.wav", ""); 

		// phrase: HaveGoodDay
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "HaveGoodDay", "HaveGoodDay.wav", ""); 

		// phrase: CollectPhoneNo
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "CollectPhoneNo", "CollectPhoneNo.wav", ""); 

		// phrase: NumberEnteredIs
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "NumberEnteredIs", "NumberEnteredIs.wav", ""); 

		// phrase: ToConfirmOrReenter
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "ToConfirmOrReenter", "ToConfirmorReenter.wav", ""); 

		// phrase: SorryExceededTries
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "SorryExceededTries", "SorryExceededTries.wav", ""); 

		// phrase: Noinput_PP
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "Noinput_PP", "NoInput_PP.wav", ""); 

		// phrase: NoMatch
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "NoMatch", "NoMatch.wav", ""); 

		//}}END:PHRASESET:STATIC
	}
	/**
	 * Returns the Phrase with the given name.  To override the
	 * behavior and dynamically return a different Phrase object,
	 * override the method "hookGetPhrase(...)".
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2023-JUL-31  10:46:36 PM
	 * @see com.avaya.sce.runtime.Phraseset#getPhrase(String) 
	 */ 
	public com.avaya.sce.runtime.Phrase getPhrase(String phraseName) {
		return(getPhrase(AllPhraseFiles.PHRASE_MAP, phraseName));
	}
}
