<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<RestWebServiceOperation version="1.0">
    <Name>AgentAPI</Name>
    <ServerUrl>https://catfact.ninja/fact</ServerUrl>
    <EndpointVariable/>
    <HttpMethod>GET</HttpMethod>
    <UseQuery>true</UseQuery>
    <OutputFormat>JSON</OutputFormat>
    <UseJavaObject>true</UseJavaObject>
    <UseBody>false</UseBody>
    <Operation>
        <Name>AgentAPI_OP</Name>
        <Inparams/>
        <Outprarms>
            <Outparam>
                <Name>fact</Name>
                <VariableName>CallBack:RestAPIResponse</VariableName>
                <IsWrapper>false</IsWrapper>
                <ShowUnwrapped>false</ShowUnwrapped>
                <ParamType>0</ParamType>
            </Outparam>
        </Outprarms>
        <Headers/>
    </Operation>
    <WebConfigParameterNames>
        <TimeoutSeconds>AgentAPI_1690783438466TimeoutSeconds</TimeoutSeconds>
        <EndpointUrl>AgentAPI_1690783438466EndpointUrl</EndpointUrl>
        <Authentication>AgentAPI_1690783438466Authentication</Authentication>
        <Password>AgentAPI_1690783438466Password</Password>
        <Username>AgentAPI_1690783438466Username</Username>
        <Preemptive>AgentAPI_1690783438466Preemptive</Preemptive>
        <Security>AgentAPI_1690783438466Security</Security>
        <Port>AgentAPI_1690783438466Port</Port>
    </WebConfigParameterNames>
    <MessageBody/>
    <Keystore/>
    <KeystorePassword/>
</RestWebServiceOperation>
