package connectivity.db.operations;

/**
 * This class is generated automatically.  Manual edits must be outside of the tagged
 * areas (for example, "START:CLASS:..." and "END:CLASS:...").  Changes within the
 * tag areas will be overwritten when the database operation is regenerated.
 * Last generated by Orchestration Designer at: 2023-JUL-10  04:49:15 PM
 */
public class Tungsten_DB extends com.avaya.sce.runtime.connectivity.db.DbQuery {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Constructor for Tungsten_DB.
	 * Last generated by Orchestration Designer at: 2023-JUL-10  04:49:15 PM
	 */
	public Tungsten_DB( com.avaya.sce.runtimecommon.IRuntimeSession mySession ) {
		//{{START:CLASS:CONSTRUCTOR
		super(mySession);

		setDataSourceName("jdbc/Tungsten_CallBack");
		setDbObjectName("dbo.Customers");
		setOperation(0);
		setReturnType(-1);
		setSQLQuery("SELECT Customers.customer_phone FROM dbo.Customers");

		// List variable that may be used
		java.util.List list;

		// Parameters
		com.avaya.sce.runtime.connectivity.db.DbQueryParam parameter;
		addParameter(new com.avaya.sce.runtime.connectivity.db.DbQueryParam("customer_phone",0,2, "CollectPhoneNo:value"));

		//}}END:CLASS:CONSTRUCTOR
	}

}

